theme = "github_dark" # default "default"

[editor]
cursorline = false
shell = ["zsh", "-c"]
color-modes = true
auto-format = true
mouse = true
bufferline = "multiple"

[editor.lsp]
auto-signature-help = true

[editor.cursor-shape]
# bar | block | underline
insert = "block"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it

[keys.normal]
G = "goto_file_end"
# Quick iteration on config changes
# C-o = ":config-open"
C-r = ":config-reload"
V = ["select_mode", "extend_to_line_bounds"]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# Muscle memory
0 = "goto_line_start"
# "$" = "goto_line_end" # default :keep-pipe
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
B = "file_picker_in_current_buffer_directory"

[keys.normal."["]
"[" = "goto_previous_buffer"

[keys.normal."]"]
"]" = "goto_next_buffer"

[keys.normal.g]
a = "code_action" # Maps `ga` to show possible code actions

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
"C-space" = "completion"  # Maps c-space to completion, default is C-x
