theme = "monokai" # default "default"

[editor]
cursorline = false
shell = ["zsh", "-c"]
color-modes = true
auto-format = true
mouse = true
bufferline = "multiple"

[editor.lsp]
auto-signature-help = true

[editor.cursor-shape]
# bar | block | underline
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
# increase value to reduce forced mid-word wrapping
max-wrap = 25         
max-indent-retain = 0
# set wrap-indicator to "" to hide it
wrap-indicator = ""

[keys.normal]
K = "hover"
G = "goto_file_end"
C-r = ":config-reload"
V = ["select_mode", "extend_to_line_bounds"]
# by default C-f/C-b(conflicts with tmux prefix) is mapped to page_down/up
C-f = "file_picker_in_current_buffer_directory" 
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.normal."["]
"[" = "goto_previous_buffer"

[keys.normal."]"]
"]" = "goto_next_buffer"

[keys.normal.g]
# Maps `ga` to show possible code actions
a = "code_action" 
# by default, gc is mapped to "GOTO view center"
# c = "toggle_commens"

[keys.insert]
# Maps `jk` to exit insert mode
j = { k = "normal_mode" } 
# Maps c-space to completion, default is C-x
"C-space" = "completion"  
[keys.select]
G = "goto_file_end"
